plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "test/sandbox/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Minitest/MultipleAssertions:
  Max: 10
